# Generated by Django 4.2 on 2023-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_service_bot', '0002_alter_service_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='TelegramUser'),
        ),
    ]
