# Generated by Django 4.2 on 2023-04-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huddle_service_bot', '0003_alter_service_service_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SubscriptionAlias',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=16, verbose_name='Alias')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='huddle_service_bot.subscription')),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliases',
                'ordering': ['subscription'],
            },
        ),
    ]
